### ISSUE TITLE
ivt meaning

### ISSUE THREAD

**Issue by Cr1t-GYM** [ucsb-seclab/hal-fuzz#2]
What is the meaning of ivt in YML file? I guess it is the interrupt vector table. For example, I browsed the maximum ivt address of the datasheet of stm32f407, which is 184. However, compared with the ivt size, 0x800000, in the stm32_tcp_echo_server.yml, it is much lower. How could I change ivt based on personal setting? 

Furthermore, some YML files point out ivt and flash in memory_map, but others point out ivt and rom. What is the difference?

Thanks for your prompt attention.

**Comment by subwire** [comment]
Indeed, IVT here means Interrupt Vector Table. Those sections don't have any special meaning based on their names, but we noticed that some chips map the firmware twice, to put their vector table in known fixed location, typically 0.
In short, if your firmware needs something at 0, put it there, else, you can safely ignore it.
